### ISSUE TITLE
Speechlet Interface (AudioPlayer / PlaybackController) Examples?

### ISSUE THREAD

**Issue by phlepper** [alexa/alexa-skills-kit-java#40]
Not an issue, per se.  

Just wondering if anyone has done anything with the AudioPlayer and / or PlaybackController interface that they'd be willing to contribute as sample code?  I'm trying to get this working, but having a bit of trouble as I'm new to the SDK, so an example of working code for using the interfaces would be helpful...

Thanks,
phlepper

**Comment by vg-appsdirect** [comment]
+1

**Comment by pavlo** [comment]
c'mon guys, don't let the people glumily shamble to node.js realm, it is so terrifying! ;-)

**Comment by sungolivia** [comment]
Thanks for bringing this to our attention, I will bring this up to the team!

**Comment by phlepper** [comment]
Thanks sungolivia!

I did get this working and would be willing to contribute, if desired (more as a sample to start from, I think, since my skills are not that great).  However, if it helps to get an example with some of the new Echo Show functionality, I'm definitely on board with that :)

phlepper
